name: Build and Publish NuGet

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest  # MAUI requires macOS for full builds

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Install MAUI Workload
        run: dotnet workload install maui

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: dotnet pack MyMauiLib/MyMauiLib.csproj --configuration Release --output ./nupkgs

      - name: Push to NuGet
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json