name: Build and Publish NuGet

on:
  push:
    tags:
      - 'v*'  # Only triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show working directory
        run: pwd

      - name: List files
        run: ls -R

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Restore dependencies
        run: dotnet restore Maui.iOS.FixedKeyboardKit/Maui.iOS.FixedKeyboardKit/Maui.iOS.FixedKeyboardKit.csproj

      - name: Build
        run: dotnet build Maui.iOS.FixedKeyboardKit/Maui.iOS.FixedKeyboardKit/Maui.iOS.FixedKeyboardKit.csproj --configuration Release --no-restore

      - name: Pack
        run: dotnet pack Maui.iOS.FixedKeyboardKit/Maui.iOS.FixedKeyboardKit/Maui.iOS.FixedKeyboardKit.csproj --configuration Release --output ./nupkgs

      - name: Push to NuGet
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json