name: Build and Publish NuGet

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug: Show working directory
        run: pwd

      - name: Debug: List all files
        run: ls -R

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Restore dependencies
        run: dotnet restore Halei.KeyboardKit.iOS/Halei.KeyboardKit.iOS/Halei.KeyboardKit.iOS.csproj

      - name: Build project
        run: dotnet build Halei.KeyboardKit.iOS/Halei.KeyboardKit.iOS/Halei.KeyboardKit.iOS.csproj --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack Halei.KeyboardKit.iOS/Halei.KeyboardKit.iOS/Halei.KeyboardKit.iOS.csproj --configuration Release --output ./nupkgs

      - name: Push to NuGet (skip duplicates)
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate